# Make sure that
#   * the revs specified here match requirements-dev.txt
#   * the additional_dependencies here match requirements.txt
repos:
-   repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    -   id: black
        args:
        - --diff
        - --check
-   repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
-   repo: https://github.com/PyCQA/pylint
    rev: v2.11.1
    hooks:
    -   id: pylint
        files: ^(telegram|examples)/.*\.py$
        args:
          - --rcfile=setup.cfg
        additional_dependencies:
          - httpx >= 0.20.0,<1.0
          - tornado>=6.1
          - APScheduler==3.6.3
          - cachetools==4.2.2
          - . # this basically does `pip install -e .`
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy
        name: mypy-ptb
        files: ^telegram/.*\.py$
        additional_dependencies:
          - types-ujson
          - types-pytz
          - types-cryptography
          - types-cachetools
          - httpx >= 0.20.0,<1.0
          - tornado>=6.1
          - APScheduler==3.6.3
          - cachetools==4.2.2
          - . # this basically does `pip install -e .`n
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade
        files: ^(telegram|examples|tests)/.*\.py$
        args:
          - --py37-plus
